### ISSUE TITLE
Cannot start the OSGIS  WPS services

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1149]
Sometimes it's not possible to reload the WPS client from OrbisGIS (OSGI services)

```
Satisfied: Immediate component: org.orbisgis.wpsclient.impl.WpsClientImpl
Got java.lang.NullPointerException when invoking "public void org.orbisgis.wpsservice.LocalWpsServerImpl.init()" in: class org.orbisgis.wpsservice.LocalWpsServerImpl
SCR getService return null because: org.osgi.service.component.ComponentException: Failed to bind: ReferenceListener(Reference LocalWpsService in Immediate component: org.orbisgis.wpsclient.impl.WpsClientImpl, target=null)
Satisfied: Immediate component: org.orbisgis.wpsservicescripts.OrbisGISWpsScriptPlugin
SCR getService return null because: org.osgi.service.component.ComponentException: Failed to bind: ReferenceListener(Reference LocalWpsService in Immediate component: org.orbisgis.wpsclient.impl.WpsClientImpl, target=null)
``

**Comment by ebocher** [comment]
It seems that this bug appears when you add an external script to the toolbox and you restart OrbisGIS.

```java

WARN in ch.qos.logback.classic.LoggerContext[null] - Error loading Logback configuration from '/home/ebocher/.OrbisGIS/5.1/logback.xml' java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at ch.qos.logback.classic.Logger.recursiveReset(Logger.java:344)
	at ch.qos.logback.classic.LoggerContext.reset(LoggerContext.java:213)
	at org.ops4j.pax.logging.logback.internal.PaxLoggingServiceImpl.configureLogbackDefaults(PaxLoggingServiceImpl.java:308)
	at org.ops4j.pax.logging.logback.internal.PaxLoggingServiceImpl.configureLogback(PaxLoggingServiceImpl.java:277)
	at org.ops4j.pax.logging.logback.internal.PaxLoggingServiceImpl.updated(PaxLoggingServiceImpl.java:242)
	at org.ops4j.pax.logging.logback.internal.PaxLoggingServiceImpl$1ManagedPaxLoggingService.updated(PaxLoggingServiceImpl.java:433)
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:148)
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:81)
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1448)
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1404)
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:103)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by nicolas-f** [comment]
May be upgrade pax logging to 1.9.1
