### ISSUE TITLE
Cannot re-open an OrbisGIS workspace

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1163]
The last release http://jenkins.orbisgis.org/job/orbisgis/425/

returns

```java
ERROR: Bundle org.orbisgis.wps-service-scripts [81] EventDispatcher: Error during dispatch. (org.osgi.service.component.ComponentException: Circular activate/deactivate detected: [ComponentConfiguration, component#34, name = org.orbisgis.wpsservicescripts.OrbisGISWpsScriptPlugin])
org.osgi.service.component.ComponentException: Circular activate/deactivate detected: [ComponentConfiguration, component#34, name = org.orbisgis.wpsservicescripts.OrbisGISWpsScriptPlugin]
	at org.knopflerfish.bundle.component.ComponentContextImpl.waitForActivation(ComponentContextImpl.java:397)
	at org.knopflerfish.bundle.component.ComponentContextImpl.setDeactivating(ComponentContextImpl.java:364)
	at org.knopflerfish.bundle.component.ComponentConfiguration.dispose(ComponentConfiguration.java:277)
	at org.knopflerfish.bundle.component.Component.disposeComponentConfigs(Component.java:671)
	at org.knopflerfish.bundle.component.Component.unsatisfied(Component.java:389)
	at org.knopflerfish.bundle.component.Component.refUnavailable(Component.java:596)
	at org.knopflerfish.bundle.component.Reference.refUnavailable(Reference.java:430)
	at org.knopflerfish.bundle.component.ReferenceListener.serviceChanged(ReferenceListener.java:480)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:943)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:794)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:544)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4445)
	at org.apache.felix.framework.Felix.access$000(Felix.java:77)
	at org.apache.felix.framework.Felix$1.serviceChanged(Felix.java:404)
	at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:153)
	at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:128)
	at org.knopflerfish.bundle.component.ComponentConfiguration.unregisterService(ComponentConfiguration.java:381)
	at org.knopflerfish.bundle.component.ComponentConfiguration.deactivate(ComponentConfiguration.java:236)
	at org.knopflerfish.bundle.component.ComponentConfiguration.ungetService(ComponentConfiguration.java:535)
	at org.apache.felix.framework.ServiceRegistrationImpl.ungetFactoryUnchecked(ServiceRegistrationImpl.java:361)
	at org.apache.felix.framework.ServiceRegistrationImpl.ungetService(ServiceRegistrationImpl.java:270)
	at org.apache.felix.framework.ServiceRegistry.ungetService(ServiceRegistry.java:407)
	at org.apache.felix.framework.Felix.ungetService(Felix.java:3588)
	at org.apache.felix.framework.BundleContextImpl.ungetService(BundleContextImpl.java:486)
	at org.knopflerfish.bundle.component.ReferenceListener.unbound(ReferenceListener.java:401)
	at org.knopflerfish.bundle.component.ComponentContextImpl.unbind(ComponentContextImpl.java:309)
	at org.knopflerfish.bundle.component.ComponentContextImpl.unbind(ComponentContextImpl.java:289)
	at org.knopflerfish.bundle.component.ComponentConfiguration.unbindReferences(ComponentConfiguration.java:615)
	at org.knopflerfish.bundle.component.ComponentConfiguration.activate(ComponentConfiguration.java:174)
	at org.knopflerfish.bundle.component.ImmediateComponent.subclassSatisfied(ImmediateComponent.java:65)
	at org.knopflerfish.bundle.component.Component.satisfied(Component.java:375)
	at org.knopflerfish.bundle.component.Component.refAvailable(Component.java:578)
	at org.knopflerfish.bundle.component.Reference.refAvailable(Reference.java:418)
	at org.knopflerfish.bundle.component.ReferenceListener.serviceChanged(ReferenceListener.java:474)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:943)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:794)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:544)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4445)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3431)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:346)
	at org.knopflerfish.bundle.component.ComponentConfiguration.registerService(ComponentConfiguration.java:351)
	at org.knopflerfish.bundle.component.ImmediateComponent.subclassSatisfied(ImmediateComponent.java:62)
	at org.knopflerfish.bundle.component.Component.satisfied(Component.java:375)
	at org.knopflerfish.bundle.component.Component.refAvailable(Component.java:578)
	at org.knopflerfish.bundle.component.Reference.refAvailable(Reference.java:418)
	at org.knopflerfish.bundle.component.ReferenceListener.serviceChanged(ReferenceListener.java:474)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:943)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:794)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:544)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4445)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3431)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:346)
	at org.knopflerfish.bundle.component.ComponentConfiguration.registerService(ComponentConfiguration.java:351)
	at org.knopflerfish.bundle.component.DelayedComponent.subclassSatisfied(DelayedComponent.java:63)

```

**Comment by ebocher** [comment]
humm if the toolbox.properties is remove the OrbisGIS works.

**Comment by nicolas-f** [comment]
This issue may be linked to that http://stackoverflow.com/questions/24570288/debug-osgi-component-activation-deactivation-issue
