### ISSUE TITLE
UI hangs when OrbisGIS is starting

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisgis#1311]
#### 1- Specifications 

* OrbisGIS version:  orbisgis-5.1.0-SNAPSHOT-2018-02-13
* Java version: 1.8
* Operating System: Windows 7 (Yep sorry, not related I swear)

#### 2- Expected behavior and actual behavior

OrbisGIS startup and ready. But got OrbisGIS hangs on restoring layout.

No error but I have a precious jstack.exe output (I've removed useless threads):

```
2018-02-23 15:50:58
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.161-b12 mixed mode):

"SwingWorker-pool-1-thread-3" #94 daemon prio=5 os_prio=0 tid=0x000000001efbf800 nid=0x25a0 waiting for monitor entry [0x000000002b61d000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.awt.Component.enable(Unknown Source)
	- waiting to lock <0x00000006c000d520> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent.enable(Unknown Source)
	at java.awt.Component.enable(Unknown Source)
	at java.awt.Component.setEnabled(Unknown Source)
	at javax.swing.JComponent.setEnabled(Unknown Source)
	at javax.swing.AbstractButton.setEnabled(Unknown Source)
	at javax.swing.JMenuItem.setEnabled(Unknown Source)
	at javax.swing.AbstractAction.setEnabledFromAction(Unknown Source)
	at javax.swing.AbstractButton.actionPropertyChanged(Unknown Source)
	at javax.swing.JMenuItem.actionPropertyChanged(Unknown Source)
	at javax.swing.AbstractButton$ButtonActionPropertyChangeListener.actionPropertyChanged(Unknown Source)
	at javax.swing.AbstractButton$ButtonActionPropertyChangeListener.actionPropertyChanged(Unknown Source)
	at javax.swing.ActionPropertyChangeListener.propertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at javax.swing.AbstractAction.firePropertyChange(Unknown Source)
	at javax.swing.AbstractAction.setEnabled(Unknown Source)
	at org.orbisgis.sqlconsole.ui.SQLConsolePanel.onUserSelectionChange(SQLConsolePanel.java:741)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.reflect.misc.Trampoline.invoke(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
	at java.beans.EventHandler.invokeInternal(Unknown Source)
	at java.beans.EventHandler.access$000(Unknown Source)
	at java.beans.EventHandler$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.beans.EventHandler.invoke(Unknown Source)
	at com.sun.proxy.$Proxy24.changedUpdate(Unknown Source)
	at javax.swing.text.AbstractDocument.fireChangedUpdate(Unknown Source)
	at org.fife.ui.rsyntaxtextarea.RSyntaxDocument.updateLastTokensBelow(RSyntaxDocument.java:612)
	at org.fife.ui.rsyntaxtextarea.RSyntaxDocument.fireInsertUpdate(RSyntaxDocument.java:180)
	at javax.swing.text.AbstractDocument.handleInsertString(Unknown Source)
	at javax.swing.text.AbstractDocument.insertString(Unknown Source)
	at javax.swing.text.PlainDocument.insertString(Unknown Source)
	at javax.swing.text.AbstractDocument.replace(Unknown Source)
	at javax.swing.text.JTextComponent.setText(Unknown Source)
	at org.orbisgis.sqlconsole.api.SQLElement.open(SQLElement.java:91)
	at org.orbisgis.sqlconsole.actions.LoadScript.doInBackground(LoadScript.java:60)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"AWT-EventQueue-0" #34 prio=6 os_prio=0 tid=0x00000000202ef800 nid=0x1654 in Object.wait() [0x0000000023ccd000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Unknown Source)
	at javax.swing.text.AbstractDocument.readLock(Unknown Source)
	- locked <0x0000000783d0ed20> (a org.fife.ui.rsyntaxtextarea.RSyntaxDocument)
	at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(Unknown Source)
	at javax.swing.plaf.basic.BasicTextAreaUI.getPreferredSize(Unknown Source)
	at javax.swing.JComponent.getPreferredSize(Unknown Source)
	at javax.swing.JTextArea.getPreferredSize(Unknown Source)
	at javax.swing.ScrollPaneLayout.layoutContainer(Unknown Source)
	at java.awt.Container.layout(Unknown Source)
	at java.awt.Container.doLayout(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validate(Unknown Source)
	- locked <0x00000006c000d520> (a java.awt.Component$AWTTreeLock)
	at javax.swing.plaf.basic.BasicTabbedPaneUI.ensureCurrentLayout(Unknown Source)
	at javax.swing.plaf.basic.BasicTabbedPaneUI.getTabBounds(Unknown Source)
	at javax.swing.JTabbedPane.getBoundsAt(Unknown Source)
	at javax.swing.JTabbedPane.setForegroundAt(Unknown Source)
	at bibliothek.gui.dock.themes.basic.BasicStackDockComponent$BasicTab.updateColors(BasicStackDockComponent.java:142)
	at bibliothek.gui.dock.themes.basic.BasicStackDockComponent$BasicTab.setController(BasicStackDockComponent.java:117)
	at bibliothek.gui.dock.station.stack.DefaultStackDockComponent.setController(DefaultStackDockComponent.java:255)
	at bibliothek.gui.dock.StackDockStation.setController(StackDockStation.java:646)
	at bibliothek.gui.dock.control.DockRegister.register(DockRegister.java:347)
	at bibliothek.gui.dock.control.DockRegister$1.handleDockable(DockRegister.java:183)
	at bibliothek.gui.dock.util.DockUtilities.visitDockable(DockUtilities.java:139)
	at bibliothek.gui.dock.util.DockUtilities.visit(DockUtilities.java:111)
	at bibliothek.gui.dock.control.DockRegister.add(DockRegister.java:180)
	at bibliothek.gui.dock.control.DockRegister.access$400(DockRegister.java:46)
	at bibliothek.gui.dock.control.DockRegister$StationListener.addDockable(DockRegister.java:647)
	at bibliothek.gui.dock.control.DockRegister$StationListener.fire(DockRegister.java:571)
	at bibliothek.gui.dock.control.DockRegister.setStalled(DockRegister.java:533)
	at bibliothek.gui.dock.support.mode.ModeManager.runTransaction(ModeManager.java:517)
	at bibliothek.gui.dock.facile.mode.LocationModeManager.runLayoutTransaction(LocationModeManager.java:505)
	at bibliothek.gui.dock.common.intern.CDockFrontend.setSetting(CDockFrontend.java:160)
	at bibliothek.gui.DockFrontend.readBlop(DockFrontend.java:2212)
	at bibliothek.gui.DockFrontend.readXML(DockFrontend.java:2131)
	at bibliothek.gui.DockFrontend.readXML(DockFrontend.java:2121)
	at bibliothek.gui.dock.common.CControl$9.readXML(CControl.java:913)
	at bibliothek.gui.dock.support.util.ApplicationResourceManager.readXML(ApplicationResourceManager.java:174)
	at bibliothek.gui.dock.common.CControl.readXML(CControl.java:2640)
	at org.orbisgis.docking.impl.DockingManagerImpl.readXML(DockingManagerImpl.java:253)
	at org.orbisgis.docking.impl.DockingManagerImpl.loadLayout(DockingManagerImpl.java:343)
	at org.orbisgis.docking.impl.DockingManagerImpl.setDockingLayoutPersistanceFilePath(DockingManagerImpl.java:470)
	at org.orbisgis.docking.impl.DockingLayoutLoader$ReloadLayout.run(DockingLayoutLoader.java:184)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)


``` 

#### 3- Steps to reproduce the problem

Start with sql console open.

#### 4 - How to fix

This method should be run into Swing thread only:

https://github.com/orbisgis/orbisgis/blob/master/bundles/sqlconsole/src/main/java/org/orbisgis/sqlconsole/ui/SQLConsolePanel.java#L720

**Comment by ebocher** [comment]
Patchs are welcome

**Comment by nicolas-f** [comment]
maven can't find the following dependencies, don't know where is the project

```xml

        <dependency>
            <groupId>org.orbiswps</groupId>
            <artifactId>client</artifactId>
            <version>${orbiswps-version}</version>
        </dependency>

        <dependency>
            <groupId>org.orbiswps</groupId>
            <artifactId>server</artifactId>
            <version>${orbiswps-version}</version>
        </dependency>
```

**Comment by ebocher** [comment]
Thank you @nicolas-f
