### ISSUE TITLE
Thread lock while opening SQLConsole

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisgis#1318]
#### 1- Specifications 

* OrbisGIS version: orbisgis-5.1.0-SNAPSHOT-2018-03-28
* Java version: 1.8
* Operating System: OpenSUSE

Issue is not systematic

#### 2- Expected behavior and actual behavior

Open SQL Console

Orbisgis Freeze

#### 3- Steps to reproduce the problem
 opening SQLConsole using Postgresql

StackTrace:

```
"AWT-EventQueue-0" #19 prio=6 os_prio=0 tid=0x00007f209c3bf000 nid=0x31ea runnable [0x00007f20d6ca9000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:143)
        at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:112)
        at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:71)
        at org.postgresql.core.PGStream.ReceiveChar(PGStream.java:269)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1704)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        - locked <0x000000076516b890> (a org.postgresql.core.v3.QueryExecutorImpl)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:560)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:283)
        at org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getProcedures(AbstractJdbc2DatabaseMetaData.java:1676)
        at org.postgresql.jdbc4.AbstractJdbc4DatabaseMetaData.getProcedures(AbstractJdbc4DatabaseMetaData.java:107)
        at org.orbisgis.sqlconsole.ui.FunctionListModel.readSQLFunctions(FunctionListModel.java:140)
        at org.orbisgis.sqlconsole.ui.FunctionListModel.getSize(FunctionListModel.java:72)
        at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1341)
        at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1310)
        at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:577)
        at javax.swing.JComponent.getPreferredSize(JComponent.java:1653)
        at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
        at java.awt.Container.layout(Container.java:1511)
        at java.awt.Container.doLayout(Container.java:1500)
        at java.awt.Container.validateTree(Container.java:1696)
        at java.awt.Container.validateTree(Container.java:1705)
        at java.awt.Container.validateTree(Container.java:1705)
        at java.awt.Container.validateTree(Container.java:1705)
        at java.awt.Container.validateTree(Container.java:1705)
        at java.awt.Container.validateTree(Container.java:1705)
        at java.awt.Container.validateTree(Container.java:1705)
        at java.awt.Container.validateTree(Container.java:1705)
        at java.awt.Container.validateTree(Container.java:1705)
        at java.awt.Container.validateTree(Container.java:1705)
        at java.awt.Container.validateTree(Container.java:1705)
        at java.awt.Container.validate(Container.java:1631)
        - locked <0x000000069e403410> (a java.awt.Component$AWTTreeLock)
        at javax.swing.plaf.basic.BasicTabbedPaneUI.ensureCurrentLayout(BasicTabbedPaneUI.java:1447)
        at javax.swing.plaf.basic.BasicTabbedPaneUI.getTabBounds(BasicTabbedPaneUI.java:1467)
        at javax.swing.JTabbedPane.getBoundsAt(JTabbedPane.java:1289)
        at javax.swing.JTabbedPane.setForegroundAt(JTabbedPane.java:1499)
        at bibliothek.gui.dock.themes.basic.BasicStackDockComponent$BasicTab.updateColors(BasicStackDockComponent.java:142)
        at bibliothek.gui.dock.themes.basic.BasicStackDockComponent$BasicTab.setController(BasicStackDockComponent.java:117)
        at bibliothek.gui.dock.station.stack.DefaultStackDockComponent.insertTab(DefaultStackDockComponent.java:148)
        at bibliothek.gui.dock.StackDockStation.insertTab(StackDockStation.java:1477)
        at bibliothek.gui.dock.StackDockStation.addToPanel(StackDockStation.java:1434)
        at bibliothek.gui.dock.StackDockStation.add(StackDockStation.java:1378)
        at bibliothek.gui.dock.StackDockStation.add(StackDockStation.java:1344)
        at bibliothek.gui.dock.StackDockStation.drop(StackDockStation.java:1182)
        at bibliothek.gui.dock.StackDockStation.drop(StackDockStation.java:1119)
        at bibliothek.gui.dock.station.split.Leaf.insert(Leaf.java:596)
        at bibliothek.gui.dock.SplitDockStation.drop(SplitDockStation.java:2201)
        at bibliothek.gui.dock.SplitDockStation.drop(SplitDockStation.java:1790)
        at bibliothek.gui.dock.common.mode.station.CSplitDockStationHandle$Normal.setLocation(CSplitDockStationHandle.java:371)
        at bibliothek.gui.dock.facile.mode.DefaultLocationMode.runApply(DefaultLocationMode.java:77)
        at bibliothek.gui.dock.facile.mode.AbstractLocationMode.apply(AbstractLocationMode.java:404)
        at bibliothek.gui.dock.facile.mode.AbstractLocationMode.apply(AbstractLocationMode.java:55)
        at bibliothek.gui.dock.support.mode.ModeManager$4.run(ModeManager.java:700)
        at bibliothek.gui.dock.support.mode.ModeManager.runTransaction(ModeManager.java:514)
        at bibliothek.gui.dock.support.mode.ModeManager.runTransaction(ModeManager.java:493)
        at bibliothek.gui.dock.support.mode.ModeManager.apply(ModeManager.java:694)
        at bibliothek.gui.dock.facile.mode.LocationModeManager.apply(LocationModeManager.java:376)
        at bibliothek.gui.dock.facile.mode.LocationModeManager.apply(LocationModeManager.java:82)
        at bibliothek.gui.dock.support.mode.ModeManager.apply(ModeManager.java:625)
        at bibliothek.gui.dock.support.mode.ModeManager.apply(ModeManager.java:561)
        at bibliothek.gui.dock.common.mode.CLocationModeManager.setLocation(CLocationModeManager.java:258)
        at bibliothek.gui.dock.common.CControl$Access.show(CControl.java:2844)
        at bibliothek.gui.dock.common.intern.AbstractCDockable.setVisible(AbstractCDockable.java:320)
        at org.orbisgis.docking.impl.internals.CustomMultipleCDockable.setVisible(CustomMultipleCDockable.java:98)
        at org.orbisgis.docking.impl.internals.OrbisGISView.init(OrbisGISView.java:174)
        at org.orbisgis.docking.impl.internals.OrbisGISView.setListeners(OrbisGISView.java:157)
        at org.orbisgis.docking.impl.DockingManagerImpl$DockingListener.added(DockingManagerImpl.java:796)
        at bibliothek.gui.dock.common.CControl.addDockable(CControl.java:1998)
        at bibliothek.gui.dock.common.CControl.addDockable(CControl.java:1949)
        at org.orbisgis.docking.impl.DockingManagerImpl.show(DockingManagerImpl.java:487)
        at org.orbisgis.docking.impl.edition.EditorManagerImpl.doOpenEditable(EditorManagerImpl.java:277)
        at org.orbisgis.docking.impl.edition.EditorManagerImpl.openEditable(EditorManagerImpl.java:286)
        at org.orbisgis.sqlconsole.MainWindowMenu.onMenuOpenSQLConsole(MainWindowMenu.java:91)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
        at java.beans.EventHandler.invokeInternal(EventHandler.java:482)
        at java.beans.EventHandler.access$000(EventHandler.java:279)
        at java.beans.EventHandler$1.run(EventHandler.java:430)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.beans.EventHandler.invoke(EventHandler.java:428)
        at com.sun.proxy.$Proxy0.actionPerformed(Unknown Source)
        at org.orbisgis.sif.components.actions.DefaultAction.actionPerformed(DefaultAction.java:149)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6533)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3315)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2237)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2295)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
        at java.awt.Container.dispatchEventImpl(Container.java:2281)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


"SwingWorker-pool-2-thread-1" #22 daemon prio=5 os_prio=0 tid=0x00007f209c407000 nid=0x31ec runnable [0x00007f20d66ab000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:143)
        at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:112)
        at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:71)
        at org.postgresql.core.PGStream.ReceiveChar(PGStream.java:269)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1704)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        - locked <0x0000000760a9c398> (a org.postgresql.core.v3.QueryExecutorImpl)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:560)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:283)
        at org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getSchemas(AbstractJdbc2DatabaseMetaData.java:2251)
        at org.postgresql.jdbc3.AbstractJdbc3DatabaseMetaData.getSchemas(AbstractJdbc3DatabaseMetaData.java:378)
        at org.h2.bnf.context.DbContents.getSchemaNames(DbContents.java:198)
        at org.h2.bnf.context.DbContents.readContents(DbContents.java:156)
        - locked <0x0000000764dff9a0> (a org.h2.bnf.context.DbContents)
        at org.orbisgis.scp.SQLCompletionProvider$UpdateParserThread.doInBackground(SQLCompletionProvider.java:241)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at javax.swing.SwingWorker.run(SwingWorker.java:334)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)




```

**Comment by ebocher** [comment]
I'm not able to reproduce this issue

**Comment by nicolas-f** [comment]
This is a thread race issue. Then it is not every time. I however post the stack trace. So it can be fixed.

**Comment by nicolas-f** [comment]
readSQLFunctions must be called only when the user click to display the list of functions, and in a background thread

**Comment by ebocher** [comment]
If you have some time. A patch is welcome. ;-)

**Comment by nicolas-f** [comment]
Fixed

**Comment by ebocher** [comment]
Merci
