### ISSUE TITLE
Unable to launch OrbisGIS with NoiseModelling

### ISSUE THREAD

**Issue by Sebastien-G** [orbisgis/orbisgis#1322]
#### 1- Specifications 

* OrbisGIS version: 5.1 (snapshot from 2018-05-17)
* Java version: Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
* Operating System: Windows 10

#### 2- Expected behavior and actual behavior

* I'm trying to launch OrbisGIS with NoiseModelling. 
* I first launched OG in safemode (with the bat file). 
* Then I created a new empty workspace. 
* Then, in the plugin manager, I installed the ```noisemap-h2-osgi (2.1.1 SNAPSHOT)``` plugin
* Then I quit and restart OG. When I'm choosing my workspace, nothing appear and I have the following log in the terminal
```
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling SLF4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Jakarta Commons Logging API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Log4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Avalon Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling JULI Logger API support.
ERROR: Bundle org.orbisgis.h2gis-osgi [24] Error starting file:/D:/Users/roadef/Downloads/orbisgis-bin/orbisgis-5.1.0-SNAPSHOT-2018-05-17/bundle/h2gis-osgi.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.orbisgis.h2gis-osgi [24]: Unable to resolve 24.0: missing requirement [24.0] osgi.wiring.package; (&(osgi.wiring.package=org.h2gis.functions.factory)(version>=1.5.0)(!(version>=2.0.0))) [caused by: Unable to resolve 91.0: missing requirement [91.0] osgi.wiring.host; (&(osgi.wiring.host=org.h2)(bundle-version>=0.0.0))])
org.osgi.framework.BundleException: Unresolved constraint in bundle org.orbisgis.h2gis-osgi [24]: Unable to resolve 24.0: missing requirement [24.0] osgi.wiring.package; (&(osgi.wiring.package=org.h2gis.functions.factory)(version>=1.5.0)(!(version>=2.0.0))) [caused by: Unable to resolve 91.0: missing requirement [91.0] osgi.wiring.host; (&(osgi.wiring.host=org.h2)(bundle-version>=0.0.0))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Unknown Source)
ERROR: Bundle org.orbisgis.jts-io-osgi [39] Error starting file:/D:/Users/roadef/Downloads/orbisgis-bin/orbisgis-5.1.0-SNAPSHOT-2018-05-17/bundle/jts-io-osgi.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.orbisgis.jts-io-osgi [39]: Unable to resolve 39.0: missing requirement [39.0] osgi.wiring.package; (osgi.wiring.package=org.locationtech.jts.geom.impl))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.orbisgis.jts-io-osgi [39]: Unable to resolve 39.0: missing requirement [39.0] osgi.wiring.package; (osgi.wiring.package=org.locationtech.jts.geom.impl)
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Unknown Source)
ERROR: Bundle org.orbisgis.postgis-jts-osgi [62] Error starting file:/D:/Users/roadef/Downloads/orbisgis-bin/orbisgis-5.1.0-SNAPSHOT-2018-05-17/bundle/postgis-jts-osgi.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.orbisgis.postgis-jts-osgi [62]: Unable to resolve 62.0: missing requirement [62.0] osgi.wiring.package; (&(osgi.wiring.package=org.orbisgis.postgis_jts)(version>=5.1.0)(!(version>=6.0.0))) [caused by: Unable to resolve 93.0: missing requirement [93.0] osgi.wiring.host; (&(osgi.wiring.host=org.h2)(bundle-version>=0.0.0))])
org.osgi.framework.BundleException: Unresolved constraint in bundle org.orbisgis.postgis-jts-osgi [62]: Unable to resolve 62.0: missing requirement [62.0] osgi.wiring.package; (&(osgi.wiring.package=org.orbisgis.postgis_jts)(version>=5.1.0)(!(version>=6.0.0))) [caused by: Unable to resolve 93.0: missing requirement [93.0] osgi.wiring.host; (&(osgi.wiring.host=org.h2)(bundle-version>=0.0.0))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Unknown Source)
ERROR: Bundle org.orbisgis.orbiswps.service [69] Error starting file:/D:/Users/roadef/Downloads/orbisgis-bin/orbisgis-5.1.0-SNAPSHOT-2018-05-17/bundle/service.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.orbisgis.orbiswps.service [69]: Unable to resolve 69.0: missing requirement [69.0] osgi.wiring.package; (&(osgi.wiring.package=org.h2gis.functions.io.geojson)(version>=1.5.0)(!(version>=2.0.0))) [caused by: Unable to resolve 91.0: missing requirement [91.0] osgi.wiring.host; (&(osgi.wiring.host=org.h2)(bundle-version>=0.0.0))])
org.osgi.framework.BundleException: Unresolved constraint in bundle org.orbisgis.orbiswps.service [69]: Unable to resolve 69.0: missing requirement [69.0] osgi.wiring.package; (&(osgi.wiring.package=org.h2gis.functions.io.geojson)(version>=1.5.0)(!(version>=2.0.0))) [caused by: Unable to resolve 91.0: missing requirement [91.0] osgi.wiring.host; (&(osgi.wiring.host=org.h2)(bundle-version>=0.0.0))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Unknown Source)
ERROR: Bundle org.orbisgis.toolbox-editor [78] Error starting file:/D:/Users/roadef/Downloads/orbisgis-bin/orbisgis-5.1.0-SNAPSHOT-2018-05-17/bundle/toolbox-editor.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.orbisgis.toolbox-editor [78]: Unable to resolve 78.0: missing requirement [78.0] osgi.wiring.package; (&(osgi.wiring.package=org.orbisgis.orbiswps.service.model)(version>=5.1.0)(!(version>=6.0.0))) [caused by: Unable to resolve 69.0: missing requirement [69.0] osgi.wiring.package; (&(osgi.wiring.package=org.h2gis.functions.io.geojson)(version>=1.5.0)(!(version>=2.0.0))) [caused by: Unable to resolve 91.0: missing requirement [91.0] osgi.wiring.host; (&(osgi.wiring.host=org.h2)(bundle-version>=0.0.0))]])
org.osgi.framework.BundleException: Unresolved constraint in bundle org.orbisgis.toolbox-editor [78]: Unable to resolve 78.0: missing requirement [78.0] osgi.wiring.package; (&(osgi.wiring.package=org.orbisgis.orbiswps.service.model)(version>=5.1.0)(!(version>=6.0.0))) [caused by: Unable to resolve 69.0: missing requirement [69.0] osgi.wiring.package; (&(osgi.wiring.package=org.h2gis.functions.io.geojson)(version>=1.5.0)(!(version>=2.0.0))) [caused by: Unable to resolve 91.0: missing requirement [91.0] osgi.wiring.host; (&(osgi.wiring.host=org.h2)(bundle-version>=0.0.0))]]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
        at java.lang.Thread.run(Unknown Source)
````

@nicolas-f @SPalominos @gpetit

**Comment by nicolas-f** [comment]
Hi,

The snapshot version of OrbisGIS is using a custom version of H2, and so, it is not compatible anymore with NoiseModelling.

Please use the prepackaged version of NoiseModelling here:

https://github.com/Ifsttar/NoiseModelling/releases/tag/2.1.1-SNAPSHOT

**Comment by Sebastien-G** [comment]
Hi,

Thanks for this quick response, it works.
