### ISSUE TITLE
Cannot load a WPS script

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis#1329]
#### 1- Specifications 

* OrbisGIS version: 5.1-dev
* Java version: 8
* Operating System: Linux

#### 2- Expected behavior and actual behavior
Load a WPS script and display the tables metadata to execute the script (table name, geometry column..)

#### 3- Steps to reproduce the problem

Load the file 
[batiments.zip](https://github.com/orbisgis/orbisgis/files/2045936/batiments.zip)

Load the WPS script "Spatial Filetring" and try to display the geometry column...
Nothing appears.

**Comment by ebocher** [comment]
Note : 
The following message is returned.
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: No enum constant org.orbisgis.orbiswps.service.model.DataType.DATE
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.orbisgis.orbiswps.service.model.DataType.valueOf(DataType.java:57)
	at org.orbisgis.orbiswps.service.model.DataType.getDataType(DataType.java:315)
	at org.orbisgis.toolboxeditor.dataui.JDBCColumnUI.populateWithColumns(JDBCColumnUI.java:507)
	at org.orbisgis.toolboxeditor.dataui.JDBCColumnUI.onComboBoxEntered(JDBCColumnUI.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
