### ISSUE TITLE
Doesn't run on linux: The workspace folder version is invalid

### ISSUE THREAD

**Issue by OnkelTem** [orbisgis/orbisgis#1346]
#### 1- Specifications 

* OrbisGIS version: 5.1.0
* Java version: 1.8
* Operating System: Linux Kubuntu 18.04

#### 2- Expected behavior and actual behavior
GUI running

#### 3- Steps to reproduce the problem
Launch the launcher script

================

I run the script and get the dialog asking to chose the workspace folder:

![launch](https://i.gyazo.com/47249cf77aab0a66b311bbfde15e6573.png)

I approve the defaults and press OK, but get the same dialog appearing for the second time. Now when I press OK one more time, the application just exits with the following error in the console:

```
2018-12-13 11:57:01,859 ERROR [WorkspaceSelectionDialog.java:368] The workspace folder version is invalid (!=OrbisGIS 5), or the folder is not empty - o.o.w.g.WorkspaceSelectionDialog
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling SLF4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Jakarta Commons Logging API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Log4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Avalon Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling JULI Logger API support.
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/h2/mvstore/MVMap$2
        at org.h2.mvstore.MVMap.entrySet(MVMap.java:827)
        at org.h2.store.LobStorageMap.removeAllForTable(LobStorageMap.java:301)
        at org.h2.engine.Database.removeOrphanedLobs(Database.java:1381)
        at org.h2.engine.Database.close(Database.java:1300)
        at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:63)
Caused by: java.lang.ClassNotFoundException: Unable to load class 'org.h2.mvstore.MVMap$2' because the bundle wiring for org.h2 is no longer valid.
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1521)
        at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more
```

**Comment by OnkelTem** [comment]
I installed H2Gis standalone, ran it, got connection credentials and changed connection details in the welcome dialog from EMBEDDED to SERVER, providing HOST/PORT.
So it seems it was a problem with EMBEDDED H2Gis.

BTW, how to provide JDBC connection line instead of HOST/PORT?

**Comment by SPalominos** [comment]
This problem seems to be linked to an OSGi wiring error. With the very last build of OrbisGIS it should be resolved and should start without error.

**Comment by OnkelTem** [comment]
Just for reference, it workes in the "safe mode" with Embedded database, more on this:
 https://github.com/orbisgis/orbisgis/issues/1347#issuecomment-447243118

**Comment by OnkelTem** [comment]
> With the very last build of OrbisGIS it should be resolved and should start without error.

I confirm that the error has gone with the latest build (5.1, thought I'm lost in versioning... wasn't it the same 5.1 which I reported, eh? Now it's the same 5.1 and it works... magick?). I mean: it doesn't show the startup dialog twice and seem to work correctly. Note that I use **embedded database**, because external one seemed to produce emtpy DB Tree (see: 
 https://github.com/orbisgis/orbisgis/issues/1347#issuecomment-447004409)

I think it can be closed.
