### ISSUE TITLE
DB tree: empty

### ISSUE THREAD

**Issue by OnkelTem** [orbisgis/orbisgis#1347]
#### 1- Specifications 

* OrbisGIS version: 5.1.0
* Java version: 1.8
* Operating System: Linux Kubuntu 18.04

#### 2- Expected behavior and actual behavior
See the list of tables

#### 3- Steps to reproduce the problem
DB Tree just empty

========
I'm not sure what I'm supposed to see since I've never used OrbisGIS before, but it doesn't look properly for me. First - I couldn't to get anything sensible from the UI: everything is empty, no visualization, almost nothing. Second, I couldn't see even the list of tables in my database. At that, I do can query data.

Example:
```
select * from timezones
```

Output:
```

Execute request 1/1: select * from timezones

PK(BIGINT)                     THE_GEOM(GEOMETRY)             TZID(CHAR)                     
1                              MULTIPOLYGON (((-5.440683 4... Africa/Abidjan                 
2                              MULTIPOLYGON (((-3.103613 5... Africa/Accra                   
3                              MULTIPOLYGON (((37.51226 14... Africa/Addis_Ababa             
4                              MULTIPOLYGON (((8.384405 35... Africa/Algiers                 
5                              MULTIPOLYGON (((43.15107 12... Africa/Asmara                  
6                              MULTIPOLYGON (((1.335369 20... Africa/Bamako                  
7                              MULTIPOLYGON (((24.216667 8... Africa/Bangui                  
8                              MULTIPOLYGON (((-16.546947 1.. Africa/Banjul                  
9                              MULTIPOLYGON (((-16.717346 1.. Africa/Bissau                  
10                             MULTIPOLYGON (((34.58596 -11.. Africa/Blantyre                
11                             MULTIPOLYGON (((17.5256 -0.7.. Africa/Brazzaville             
12                             MULTIPOLYGON (((30.185424 -4.. Africa/Bujumbura               
13                             MULTIPOLYGON (((34.732701 26.. Africa/Cairo                   
14                             MULTIPOLYGON (((-5.11191 36... Africa/Casablanca              
15                             MULTIPOLYGON (((-5.418489 35.. Africa/Ceuta                   
16                             MULTIPOLYGON (((-15.101679 1.. Africa/Conakry                 
17                             MULTIPOLYGON (((-16.5049 16... Africa/Dakar                   
18                             MULTIPOLYGON (((40.423605 -1.. Africa/Dar_es_Salaam           
...
```

But the list in DB Tree has only two default items: INFORMATION_SCHEMA and PUBLIC - both empty. No my "timezones" table or anything else.

**Comment by SPalominos** [comment]
Some fix have been done and might change the behavior of OrbisGIS, could you retry with the very last build ?

**Comment by OnkelTem** [comment]
> Some fix have been done and might change the behavior of OrbisGIS, could you retry with the very last build ?

I would gladly do it, if only I knew where to get it :) 
GitHub releases pages doesn't seem to be maintained.
I couldn't find this information on your homepage either.

**Comment by ebocher** [comment]
Go to http://orbisgis.org/ and DOWNLOAD section : Click on the image below to download the V5.1 Molene – Snapshot (based on H2GIS). 
@gpetit

**Comment by OnkelTem** [comment]
Sorry but... isn't that what I use currently? I think it is: **orbisgis-5.1.0-SNAPSHOT-2018-12-13**

**Comment by SPalominos** [comment]
To complete @ebocher  answer : 
If you have downloaded OrbisGIS through the PPA, you just have to do an `apt update` and `apt upgrade` and then lanch it with the clean option : `orbisgis -clean`
If you have downloaded the zip, redownload it on http://orbisgis.org, unzip it and launch `orbisgis_safemode.sh`

**Comment by OnkelTem** [comment]
Ok guys, I downloaded it one more time from here:
http://jenkins.orbisgis.org/job/orbisgis-5.1-dev/lastSuccessfulBuild/artifact/orbisgis-dist/target/orbisgis-bin.zip

It was unpacked into the same folder `orbisgis-5.1.0-SNAPSHOT-2018-12-13` and I launched in one more time.

Both `orbisgis.sh` and `orbisgis_safe.sh` produce the same UI state without visible differences.
DB Tree is still empty.

There are some message in the Output pane, but only few are of red color:
```
Cannot read the table list
```
and
```
Table "SYNONYMS" not found; SQL statement:
SELECT TABLE_CAT, TABLE_SCHEM, TABLE_NAME, TABLE_TYPE, REMARKS, TYPE_CAT, TYPE_SCHEM, TYPE_NAME, SELF_REFERENCING_COL_NAME, REF_GENERATION, SQL FROM (SELECT SYNONYM_CATALOG TABLE_CAT, SYNONYM_SCHEMA TABLE_SCHEM, SYNONYM_NAME as TABLE_NAME, TYPE_NAME AS TABLE_TYPE, REMARKS, TYPE_NAME TYPE_CAT, TYPE_NAME TYPE_SCHEM, TYPE_NAME AS TYPE_NAME, TYPE_NAME SELF_REFERENCING_COL_NAME, TYPE_NAME REF_GENERATION, NULL AS SQL FROM INFORMATION_SCHEMA.SYNONYMS WHERE SYNONYM_CATALOG LIKE ? ESCAPE ? AND SYNONYM_SCHEMA LIKE ? ESCAPE ? AND SYNONYM_NAME LIKE ? ESCAPE ? AND (true)  UNION SELECT TABLE_CATALOG TABLE_CAT, TABLE_SCHEMA TABLE_SCHEM, TABLE_NAME, TABLE_TYPE, REMARKS, TYPE_NAME TYPE_CAT, TYPE_NAME TYPE_SCHEM, TYPE_NAME, TYPE_NAME SELF_REFERENCING_COL_NAME, TYPE_NAME REF_GENERATION, SQL FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_CATALOG LIKE ? ESCAPE ? AND TABLE_SCHEMA LIKE ? ESCAPE ? AND TABLE_NAME LIKE ? ESCAPE ? AND (TABLE_TYPE IN(?, ?, ?, ?, ?, ?, ?)) ) ORDER BY TABLE_TYPE, TABLE_SCHEM, TABLE_NAME [42102-197]
Cannot read the table list
```

Further ideas? I'm eager to try whatever you ask me to.

**Comment by SPalominos** [comment]
Did you use the embedded database (the default one) or did you connect OrbisGIS to an already existing database (which one : H2 or postgis) ?

Can you give us the output of the terminal when you launch `orbisgis_safemode.sh` ?

**Comment by OnkelTem** [comment]
> Did you use the embedded database (the default one) or did you connect OrbisGIS to an already existing database (which one : H2 or postgis) ?

I used external H2. Now when I switched to embedded it's started working finally!

![OSM+Timezones](https://i.gyazo.com/f03cacd1ae04eaa0c6c54b0bc4315379.png)

Thank you for pointing this out.

> Can you give us the output of the terminal when you launch orbisgis_safemode.sh ?

Well, in contrast to launching `orbisgis.sh`,  `orbisgis_safemode.sh` produces no errors:

```
$ ./orbisgis_safemode.sh
Safe mode engaged, clear the following folder in 5 seconds..
/home/<user>/.OrbisGIS/5.1/cache
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling SLF4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Jakarta Commons Logging API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Log4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Avalon Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling JULI Logger API support.
```

However when exiting I get one exception:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.orbisgis.coremap.layerModel.Layer.getUniqueColumnIdentifier(Layer.java:326)
        at org.orbisgis.mapeditor.map.tools.IntersectsSelectionTool.isEnabled(IntersectsSelectionTool.java:79)
        at org.orbisgis.mapeditor.map.toolbar.ActionAutomaton.checkActionState(ActionAutomaton.java:134)
        at org.orbisgis.mapeditor.map.toolbar.ActionMapContext.isEnabled(ActionMapContext.java:110)
        at org.orbisgis.docking.impl.internals.actions.CommonFunctions.onActionPropertyChangeDecorateable(CommonFunctions.java:96)
        at org.orbisgis.docking.impl.internals.actions.CToggleButton.<init>(CToggleButton.java:60)
        at org.orbisgis.docking.impl.internals.actions.ToolBarActions.setActions(ToolBarActions.java:170)
        at org.orbisgis.docking.impl.internals.OrbisGISView.onSetActions(OrbisGISView.java:225)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
        at java.beans.EventHandler.invokeInternal(EventHandler.java:482)
        at java.beans.EventHandler.access$000(EventHandler.java:279)
        at java.beans.EventHandler$1.run(EventHandler.java:430)
        at java.security.AccessController.doPrivileged(Native Method)                                                                                                                                                                                                          
        at java.beans.EventHandler.invoke(EventHandler.java:428)                                                                                                                                                                                                               
        at com.sun.proxy.$Proxy1.propertyChange(Unknown Source)                                                                                                                                                                                                                
        at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)                                                                                                                                                                                               
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)                                                                                                                                                                                 
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)                                                                                                                                                                                 
        at org.orbisgis.sif.docking.DockingPanelParameters.setDockActions(DockingPanelParameters.java:387)                                                                                                                                                                     
        at org.orbisgis.sif.components.actions.ActionDockingListener$CopyActionsProcess.run(ActionDockingListener.java:99)                                                                                                                                                     
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)                                                                                                                                                                                                   
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)                                                                                                                                                                                                          
        at java.awt.EventQueue.access$500(EventQueue.java:97)                                                                                                                                                                                                                  
        at java.awt.EventQueue$3.run(EventQueue.java:709)                                                                                                                                                                                                                      
        at java.awt.EventQueue$3.run(EventQueue.java:703)                                                                                                                                                                                                                      
        at java.security.AccessController.doPrivileged(Native Method)                                                                                                                                                                                                          
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)                                                                                                                                                             
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)                                                                                                                                                                                                              
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)                                                                                                                                                                                   
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)                                                                                                                                                                                      
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)                                                                                                                                                                                   
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)                                                                                                                                                                                               
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)                                                                                                                                                                                                
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)                                                                                                                                                                                                       
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling SLF4J API support.                                                                                                                                                                 
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Jakarta Commons Logging API support.                                                                                                                                               
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Log4J API support.                                                                                                                                                                 
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Avalon Logger API support.                                                                                                                                                         
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling JULI Logger API support.
```

**Comment by OnkelTem** [comment]
So guys, if I get it right, there's only one issue left to address: why it doesn't work with external H2Gis, right?

**Comment by SPalominos** [comment]
Exact, we are working on it and we will fix it as soon as possible !

**Comment by ebocher** [comment]
Closed OrbisGIS UI dev stopped.
