### ISSUE TITLE
DBeaver and .m2

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/orbisgis#1356]
Sorry I did not kinow where to put this issue...

I have deleted the .m2 folder in order to update my geoclimate package. Then when I launch a script using 
```groovy
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT')

import org.orbisgis.orbisprocess.geoclimate.Geoclimate
```
The .m2 file is not reloaded. Is it a correct behavior ? Note that the similar behavior is met using the groovyConsole.

**Comment by ebocher** [comment]
You can put the issue here https://github.com/orbisgis/orbisrcp

**Comment by j3r3m1** [comment]
I do not have any option to move the issue on the right side-bar. Problem of rights ?

**Comment by j3r3m1** [comment]
OK I realize that the problem may come from the fact that DBeaver or GroovyConsole have nothing to do with .m2 folder. Actually to make DBeaver download a new version of geoclimate, I suppose that it is necessary to delete the .groovy folder.

I have done that, however, I have the following error when using the grab resolver:
> java.lang.RuntimeException: Error grabbing Grapes -- [download failed: net.sourceforge.f2j#arpack_combined_all;0.1!arpack_combined_all.jar]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
