### ISSUE TITLE
JGraphT Bundle loading error

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#750]
JGraphT duplicate loading error.

```
org.osgi.framework.BundleException: Bundle symbolic name and version are not unique: org.jgrapht:0.8.4.dev
	at org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1305)
	at org.apache.felix.framework.BundleImpl.<init>(BundleImpl.java:112)
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2907)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:165)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:138)
	at org.orbisgis.core.plugin.BundleTools.installBundles(BundleTools.java:347)
	at org.orbisgis.core.context.main.MainContext.startBundleHost(MainContext.java:123)
	at org.orbisgis.view.main.Core.startPluginHost(Core.java:180)
	at org.orbisgis.view.main.Core.<init>(Core.java:163)
	at org.orbisgis.view.main.CoreLauncher.launch(CoreLauncher.java:117)
	at org.orbisgis.view.main.Main.main(Main.java:81)
```

**Comment by nicolas-f** [comment]
A can't reproduce this issue. Maybe it has been fixed when OSGi integration was complete ?
