### ISSUE TITLE
Error when trying to zoom on a selection in the table editor

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#821]
In the V5.1, I'm connected to a Postgis db.

In the table editor, I selected an object and I clicked on "zoom to selection". Then I obtain this error message

```
3449000 [SwingWorker-pool-2-thread-2] ERROR o.o.c.p.ZoomToSelectedFeatures - Impossible d'établir l'enveloppe de la sélection
 org.postgresql.util.PSQLException: L'indice de la colonne est hors limite : -1, nombre de colonnes : 1.
	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.checkColumnIndex(AbstractJdbc2ResultSet.java:2845)
	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.checkResultSet(AbstractJdbc2ResultSet.java:2862)
	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.getObject(AbstractJdbc2ResultSet.java:2690)
	at org.orbisgis.postgis_jts_osgi.ResultSetWrapper.getObject(ResultSetWrapper.java:98)
	at org.h2gis.utilities.wrapper.ResultSetWrapper.getObject(ResultSetWrapper.java:234)
	at org.h2gis.utilities.wrapper.SpatialResultSetImpl.getGeometry(SpatialResultSetImpl.java:29)
	at org.h2gis.utilities.wrapper.SpatialResultSetImpl.getGeometry(SpatialResultSetImpl.java:55)
	at org.orbisgis.corejdbc.ReadTable.getTableSelectionEnvelope(ReadTable.java:390)
	at org.orbisgis.coremap.process.ZoomToSelectedFeatures.doInBackground(ZoomToSelectedFeatures.java:72)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Note that the geometric field is named "wkb_geometry"

@nicolas-f @ebocher

**Comment by nicolas-f** [comment]
ST_EXTENT in postgis return a BOX2D not a geometry. Have to customise the sql request for postgre or enhance orbisgis driver to manage box2d to geometry conversion.

**Comment by ebocher** [comment]
@gpetit  please test it

**Comment by ebocher** [comment]
Thanks it works
