### ISSUE TITLE
OG is not drawing

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis#870]
I downloaded the last snapshot today and I have some problem with the drawing part.

In a new empty workspace, I just imported the "COMMUNE" layer from GeoFLA. Then I draged and droped it into the TOC --> nothing, no drawing ... even if the table is full of fields and lines...

After many refresh (restart the workspace, full extent zoom, refresh the map, change the map, ...) the layer is drawn.

So the problem appears to be random

@ebocher

**Comment by nicolas-f** [comment]
traceback

```
8018 [AWT-EventQueue-0] ERROR g.c.o.d.impl.DockingManagerImpl - null
 java.lang.NullPointerException: null
	at java.util.LinkedList$ListItr.next(LinkedList.java:893)
	at bibliothek.gui.dock.util.UIProperties.remove(UIProperties.java:493)
	at bibliothek.gui.dock.util.AbstractUIValue.setManager(AbstractUIValue.java:176)
	at bibliothek.gui.dock.util.icon.DockIcon.setController(DockIcon.java:69)
	at bibliothek.gui.dock.dockable.AbstractDockable.setController(AbstractDockable.java:190)
	at bibliothek.gui.dock.AbstractToolbarDockStation.setController(AbstractToolbarDockStation.java:183)
	at bibliothek.gui.dock.ToolbarGroupDockStation.setController(ToolbarGroupDockStation.java:549)
	at bibliothek.gui.dock.ToolbarContainerDockStation.add(ToolbarContainerDockStation.java:1082)
	at bibliothek.gui.dock.ToolbarContainerDockStation.add(ToolbarContainerDockStation.java:1068)
	at bibliothek.gui.dock.ToolbarContainerDockStation.drop(ToolbarContainerDockStation.java:811)
	at bibliothek.gui.dock.ToolbarContainerDockStation.drop(ToolbarContainerDockStation.java:777)
	at bibliothek.gui.dock.toolbar.location.CToolbarAreaHandle.setLocation(CToolbarAreaHandle.java:92)
	at bibliothek.gui.dock.facile.mode.DefaultLocationMode.runApply(DefaultLocationMode.java:77)
	at bibliothek.gui.dock.facile.mode.AbstractLocationMode.apply(AbstractLocationMode.java:384)
	at bibliothek.gui.dock.facile.mode.AbstractLocationMode.apply(AbstractLocationMode.java:54)
	at bibliothek.gui.dock.support.mode.ModeManager$4.run(ModeManager.java:698)
	at bibliothek.gui.dock.support.mode.ModeManager.runTransaction(ModeManager.java:512)
	at bibliothek.gui.dock.support.mode.ModeManager.runTransaction(ModeManager.java:491)
	at bibliothek.gui.dock.support.mode.ModeManager.apply(ModeManager.java:692)
	at bibliothek.gui.dock.support.mode.ModeManager.apply(ModeManager.java:623)
	at bibliothek.gui.dock.support.mode.ModeManager.apply(ModeManager.java:559)
	at bibliothek.gui.dock.common.mode.CLocationModeManager.setLocation(CLocationModeManager.java:258)
	at bibliothek.gui.dock.common.CControl$Access.show(CControl.java:2710)
	at bibliothek.gui.dock.common.intern.AbstractCDockable.setVisible(AbstractCDockable.java:315)
	at org.orbisgis.docking.impl.DockingManagerImpl.setLocation(DockingManagerImpl.java:649)
	at org.orbisgis.docking.impl.DockingManagerImpl.addToolbarItem(DockingManagerImpl.java:585)
	at org.orbisgis.docking.impl.DockingManagerImpl.resetToolBarsCActions(DockingManagerImpl.java:720)
	at org.orbisgis.docking.impl.DockingManagerImpl.readXML(DockingManagerImpl.java:284)
	at org.orbisgis.docking.impl.DockingManagerImpl.loadLayout(DockingManagerImpl.java:334)
	at org.orbisgis.docking.impl.DockingManagerImpl.setDockingLayoutPersistanceFilePath(DockingManagerImpl.java:461)
	at org.orbisgis.docking.impl.DockingLayoutLoader$ReloadLayout.run(DockingLayoutLoader.java:176)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

and

```
54629 [SwingWorker-pool-2-thread-1] ERROR org.orbisgis.docking-impl - Got java.util.ConcurrentModificationException when invoking "public void org.orbisgis.docking.impl.DockingManagerImpl.addToolBarFactory(org.orbisgis.mainframe.api.ToolBarAction)" in: class org.orbisgis.docking.impl.DockingManagerImpl
 java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.knopflerfish.bundle.component.ComponentMethod$Operation.invoke(ComponentMethod.java:322)
	at org.knopflerfish.bundle.component.ComponentContextImpl.bind(ComponentContextImpl.java:240)
	at org.knopflerfish.bundle.component.ComponentConfiguration.bindReference(ComponentConfiguration.java:458)
	at org.knopflerfish.bundle.component.ReferenceListener.bindReference(ReferenceListener.java:657)
	at org.knopflerfish.bundle.component.ReferenceListener.refAdded(ReferenceListener.java:564)
	at org.knopflerfish.bundle.component.ReferenceListener.serviceChanged(ReferenceListener.java:475)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:943)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:794)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:544)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4445)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3431)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:346)
	at org.knopflerfish.bundle.component.ComponentConfiguration.registerService(ComponentConfiguration.java:351)
	at org.knopflerfish.bundle.component.DelayedComponent.subclassSatisfied(DelayedComponent.java:63)
	at org.knopflerfish.bundle.component.Component.satisfied(Component.java:375)
	at org.knopflerfish.bundle.component.Component.refAvailable(Component.java:578)
	at org.knopflerfish.bundle.component.Reference.refAvailable(Reference.java:418)
	at org.knopflerfish.bundle.component.ReferenceListener.serviceChanged(ReferenceListener.java:474)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:943)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:794)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:544)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4445)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3431)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:346)
	at org.knopflerfish.bundle.component.ComponentConfiguration.registerService(ComponentConfiguration.java:351)
	at org.knopflerfish.bundle.component.DelayedComponent.subclassSatisfied(DelayedComponent.java:63)
	at org.knopflerfish.bundle.component.Component.satisfied(Component.java:375)
	at org.knopflerfish.bundle.component.Component.refAvailable(Component.java:578)
	at org.knopflerfish.bundle.component.Reference.refAvailable(Reference.java:418)
	at org.knopflerfish.bundle.component.ReferenceListener.serviceChanged(ReferenceListener.java:474)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:943)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:794)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:544)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4445)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3431)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:346)
	at org.knopflerfish.bundle.component.ComponentConfiguration.registerService(ComponentConfiguration.java:351)
	at org.knopflerfish.bundle.component.DelayedComponent.subclassSatisfied(DelayedComponent.java:63)
	at org.knopflerfish.bundle.component.Component.satisfied(Component.java:375)
	at org.knopflerfish.bundle.component.Component.refAvailable(Component.java:578)
	at org.knopflerfish.bundle.component.Reference.refAvailable(Reference.java:418)
	at org.knopflerfish.bundle.component.ReferenceListener.serviceChanged(ReferenceListener.java:474)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:943)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:794)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:544)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4445)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3431)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:346)
	at org.knopflerfish.bundle.component.ComponentConfiguration.registerService(ComponentConfiguration.java:351)
	at org.knopflerfish.bundle.component.DelayedComponent.subclassSatisfied(DelayedComponent.java:63)
	at org.knopflerfish.bundle.component.Component.satisfied(Component.java:375)
	at org.knopflerfish.bundle.component.Component.refAvailable(Component.java:578)
	at org.knopflerfish.bundle.component.Reference.refAvailable(Reference.java:418)
	at org.knopflerfish.bundle.component.ReferenceListener.serviceChanged(ReferenceListener.java:474)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:943)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:794)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:544)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4445)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3431)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:346)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:353)
	at org.orbisgis.wkgui.gui.WorkspaceSelectionDialog$RegisterViewWorkspaceJob.doInBackground(WorkspaceSelectionDialog.java:394)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at bibliothek.gui.dock.common.CControl.getSingleDockable(CControl.java:1685)
	at org.orbisgis.docking.impl.DockingManagerImpl.addToolbarItem(DockingManagerImpl.java:572)
	at org.orbisgis.docking.impl.DockingManagerImpl.resetToolBarsCActions(DockingManagerImpl.java:720)
	at org.orbisgis.docking.impl.DockingManagerImpl.addActions(DockingManagerImpl.java:542)
	at org.orbisgis.docking.impl.DockingManagerImpl.addActionFactory(DockingManagerImpl.java:754)
	at org.orbisgis.docking.impl.DockingManagerImpl.addToolBarFactory(DockingManagerImpl.java:741)
	... 72 common frames omitted
```

**Comment by ebocher** [comment]
so we must update the last docking frame ?

**Comment by nicolas-f** [comment]
Yes. The traceback always end at bibliothek.gui.dock, this is Docking Frames.

**Comment by ebocher** [comment]
@nicolas-f could you please update the DF lib ?

**Comment by nicolas-f** [comment]
The update does not fix the problem. Have to fix it on docking frames then create a PR..

**Comment by ebocher** [comment]
Ok thanks a lot.

**Comment by ebocher** [comment]
@gpetit  Could you confirm this fix ?

**Comment by nicolas-f** [comment]
I said ```The update does not fix the problem.```

**Comment by ebocher** [comment]
@gpetit  Fixed ?

**Comment by ebocher** [comment]
@gpetit Fixed ?

**Comment by gpetit** [comment]
Seems to work (can not reproduce with the last snapshot).

Thx
